apiVersion: v2
name: k8s-cicd-lab
description: A Helm chart for the k8s-cicd-lab application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
  - name: postgresql
    version: 18.2.3
    repository: https://charts.bitnami.com/bitnami